import type { ProjectVisualVariant } from "@/components/visual/ProjectVisual";

export const defaultContent = {
  key: "main",
  brand: { name: "SEXIMON", logoText: "SEXIMON" },
  home: {
    label: "3D Design · Animation · Visual Storytelling",
    titleLine1: "Bringing Ideas",
    titleLine2: "to Life in",
    titleHighlight: "3D",
    description: "I create clean, cinematic 3D visuals and motion experiences full of character.",
    buttonText: "Explore Work",
    counterText: "02 /05 Selected Projects",
    quote: "I don’t just create visuals, I tell stories that connect.",
    quoteAuthor: "Seximon",
  },
  work: {
    label: "My Work",
    featuredTitle: "Featured",
    featuredHighlight: "Projects",
    featuredDescription: "A selection of recent 3D, animation, branding and motion projects.",
    allTitle: "All",
    allHighlight: "Projects",
    allDescription: "Explore my complete collection of visual, motion and 3D work.",
    categories: ["All Categories", "3D Animation", "Character Design", "Product Visual", "Branding", "Motion Graphics", "Instagram Design"],
    projects: [
      { number: "01", title: "Abstract Motion", category: "3D Animation", variant: "abstract-motion" as ProjectVisualVariant },
      { number: "02", title: "Product Animation", category: "3D Animation", variant: "product-ring" as ProjectVisualVariant },
      { number: "03", title: "Character Design", category: "3D Character", variant: "character" as ProjectVisualVariant },
      { number: "04", title: "Brand Visual", category: "Branding", variant: "brand-symbol" as ProjectVisualVariant },
      { number: "05", title: "Motion Graphics", category: "Motion Design", variant: "motion-sphere" as ProjectVisualVariant },
      { number: "06", title: "Futuristic Helmet", category: "3D Design", variant: "helmet" as ProjectVisualVariant },
      { number: "07", title: "Glass Cube", category: "3D Animation", variant: "glass-cube" as ProjectVisualVariant },
      { number: "08", title: "Sneaker Visual", category: "Product Visual", variant: "sneaker" as ProjectVisualVariant },
      { number: "09", title: "Bottle Campaign", category: "Product Visual", variant: "bottle" as ProjectVisualVariant },
      { number: "10", title: "Watch Visual", category: "Product Visual", variant: "watch" as ProjectVisualVariant },
      { number: "11", title: "Social Campaign", category: "Instagram Design", variant: "instagram" as ProjectVisualVariant },
      { number: "12", title: "Poster Design", category: "Branding", variant: "abstract-motion" as ProjectVisualVariant },
    ],
    instagramTitle: "Instagram Projects",
    instagramDescription: "Social media layouts and campaign visuals.",
    instagramBadge: "12+",
    instagramProjects: [
      { number: "01", title: "Coffee Land", category: "Instagram Design", variant: "motion-sphere" as ProjectVisualVariant },
      { number: "02", title: "Fit Move", category: "Instagram Design", variant: "character" as ProjectVisualVariant },
      { number: "03", title: "Glow Skincare", category: "Instagram Design", variant: "bottle" as ProjectVisualVariant },
      { number: "04", title: "Travel More", category: "Instagram Design", variant: "glass-cube" as ProjectVisualVariant },
      { number: "05", title: "Burger House", category: "Instagram Design", variant: "motion-sphere" as ProjectVisualVariant },
      { number: "06", title: "Minimal Interior", category: "Instagram Design", variant: "instagram" as ProjectVisualVariant },
      { number: "07", title: "Tech Future", category: "Instagram Design", variant: "brand-symbol" as ProjectVisualVariant },
    ],
  },
  about: {
    label: "About Me",
    titleLine1: "I’m Designer &",
    titleHighlight: "3D Animator",
    description: "I craft visual experiences that combine creativity, technology, and emotion into cinematic digital storytelling.",
    buttonText: "View My Work",
    stats: ["5+ Years", "200+ Projects", "50+ Clients"],
    services: [
      { title: "3D Design", text: "Creating stunning 3D models and scenes." },
      { title: "Animation", text: "Bringing ideas to life through smooth animation." },
      { title: "Visual Storytelling", text: "Turning concepts into compelling narratives." },
      { title: "Branding", text: "Designing visual identities that stand out." },
    ],
    tools: ["Blender", "Ae", "Ps", "Ai", "C4D", "Figma"],
    approachLabel: "My Approach",
    approachTitle: "My Creative",
    approachHighlight: "Approach",
    approachSteps: [
      { number: "01", title: "Discover", text: "Understanding the concept, goals, and audience." },
      { number: "02", title: "Design", text: "Crafting visuals and planning the story." },
      { number: "03", title: "Develop", text: "Bringing everything to life with precision." },
      { number: "04", title: "Deliver", text: "Delivering high-quality work that makes impact." },
    ],
  },
  experience: {
    label: "Experience",
    titleLine1: "My",
    titleHighlight: "Experience",
    description: "My professional journey and career highlights.",
    stats: ["200+ Projects", "5+ Years", "50+ Clients"],
    items: [
      { year: "2023 – Present", title: "Freelance Designer & 3D Animator", text: "Working with amazing clients worldwide on 3D and motion projects." },
      { year: "2021 – 2023", title: "3D Animator", text: "Created 3D animations and visual content for digital campaigns." },
      { year: "2019 – 2021", title: "Motion Designer", text: "Designed motion graphics and visual content for brands." },
      { year: "2017 – 2019", title: "Graphic Designer", text: "Worked on branding, social media design, and digital content." },
    ],
  },
  process: {
    label: "My Approach",
    titleLine1: "My Creative",
    titleHighlight: "Process",
    description: "A clear process that turns ideas into impactful visual experiences.",
    steps: [
      { number: "01", title: "Discover", text: "Understanding the concept, audience, and creative direction." },
      { number: "02", title: "Design", text: "Crafting visual systems, moodboards, and strong compositions." },
      { number: "03", title: "Develop", text: "Building 3D scenes, motion, lighting, and production details." },
      { number: "04", title: "Deliver", text: "Finalizing polished outputs that feel premium and memorable." },
    ],
  },
  contact: {
    label: "Contact Me",
    titleLine1: "Let’s Work",
    titleHighlight: "Together",
    description: "Have a project in mind? I’d love to hear from you.",
    fields: ["Your Name", "Your Email", "Project Type", "Your Message"],
    buttonText: "Send Message",
    cards: [
      { label: "Email", value: "hello@seximon.com", type: "email" },
      { label: "Phone", value: "+98 912 345 6789", type: "phone" },
      { label: "Location", value: "Tehran, Iran", type: "location" },
      { label: "Instagram", value: "@seximon.design", type: "instagram" },
    ],
  },
};

export type SiteContentShape = typeof defaultContent;
